# -*- coding: utf-8 -*-
"""COP1000_Module05_TipCalculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IsdfwB720aCwSA2cx47BmbZ3mOOc63Rd
"""

#inputs
bill=float(input("What was the total bill: $"))
tip=float(input("Tip percentage: "))

#tip calc
def calculate_tip(bill, tip):
  tip=tip/100
  total=(bill*tip)+bill
  print(f"The total cost is: ${total:.2f}")

calculate_tip(bill, tip)