# -*- coding: utf-8 -*-
"""COP1000_Module02_PersonalInformation.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LL0o3OclrkV-J8OzoctG1hHVWRX3VkNC
"""

#inputs for the summary
#First name, Last name, Age, City, Academic major or career interest
firstname= input("First name: ")
lastname= input("Last name: ")
age= input("Age: ")
age= int(age)
next_birthday= age + 1
city= input("City: ")
major= input("Academic major or career interest: ")
#displaying results
print(f"\n---Personal Information---\n \n Name: {firstname} {lastname}\n Age: {age}\n Age Next Year: {next_birthday}\n City: {city}\n Major or Interest: {major}")

