# -*- coding: utf-8 -*-
"""COP1000_Module01_HelloPython.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lr7SLYqDDC2_yy8Vg43VWj6ocHCjlo3f
"""

# Includes at least four print() statements.
# Includes at least one comment.
# Displays a short introduction.
# Displays your academic or career interest.
# Displays something you hope to learn in Python
# Displays a closing or welcome message.
# Runs without syntax errors.

# print statements

print("Hello., my name is Aiden and im taking COP1000!")
print("My academic interests are computers. Both software and hardware elements.")
print("I hope to learn how to make an interactive program to eventually build into a small, homemade game.")
print("Heres a closing message!")