# -*- coding: utf-8 -*-
"""COP1000_Module03_DecisionTool

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xtOayrvppMvdPWOCGvVbmFVm5MSrN03R
"""

#current weather
temp= input("What is the current temperature? ")
temp= int(temp)
rain= input("Is it raining? ")

#recommended activities
if rain.lower() == "yes":
  print("I would recommend an inside activity like playing video games")
elif temp<=60:
  print("I would recommend a cool outside activity like skiing")
elif temp>60 and temp<=84:
  print("I would recommend a warm outside activity like hiking")
else:
  print("I would recommend a hot outside activity like going to the pool or the beach")