# -*- coding: utf-8 -*-
"""COP1000_Module04_GuessTheNumber.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q4oc5J1434mOegTjase-2_SZwTh2sUIT
"""

#import run this cell first
import random
secret_number=random.randint(1,20)

#user input
user_input=input("Guess the random number 1-20 ")
user_input=int(user_input)
attempt=0
while user_input!=secret_number:
  if user_input > secret_number:
    print("The number is lower")
  else:
    print("The number is higher")
  user_input = int(input("Try again: "))
  attempt+=1
print(f"You guessed it! The secret number was {secret_number}, in {attempt} amount of attempts")